name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: nasm
      uses: ilammy/setup-nasm@v1.4.0
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: kernel xd
        # A file, directory or wildcard pattern that describes what to upload
        path: kernel.bin
